### ISSUE TITLE
The program crashes due to the implementation of some mod methods

### ISSUE THREAD

**Issue by lingting** [qw2341/Loadout-Mod#4]
When using the Monster in a Bottle feature ,Can I automatically skip the monsters in the mod that cause crashes?

`
Mods in stacktrace:
 - Library of Ruina (1.1.6)
 - loadout (0.9.7)
Cause:
java.lang.NullPointerException
	at com.megacrit.cardcrawl.monsters.AbstractMonster.createIntent(AbstractMonster.java:479)
	at lor.monster.AbstractNeutralMonster.update(AbstractNeutralMonster.java:43)
	at lor.monster.nihil.LibrarianWrath.update(LibrarianWrath.java:127)
	at loadout.screens.MonsterSelectScreen$MonsterButton.update(MonsterSelectScreen.java:226)
	at loadout.screens.MonsterSelectScreen.updateList(MonsterSelectScreen.java:504)
	at loadout.screens.AbstractSelectScreen.update(AbstractSelectScreen.java:275)
	at loadout.relics.AbstractCustomScreenRelic.update(AbstractCustomScreenRelic.java:171)
	at loadout.relics.AllInOneBag.update(AllInOneBag.java:255)
	at com.megacrit.cardcrawl.core.OverlayMenu.update(OverlayMenu.java:71)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2649)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

**Comment by qw2341** [comment]
Hi, thank you for reporting. I will try to add a try catch to the method call to prevent crashing.
